version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@3.0.1


jobs:
  build:
    docker:
      - image: circleci/ruby:2.6-node
    working_directory: ~/study_support_app
    steps:
      - checkout:
          path: ~/study_support_app
      - ruby/install-deps
      - run: yarn install

  test:
    docker:
      - image: circleci/ruby:2.6-node
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: app_user_role
          POSTGRES_DB: study_support_app_test
          POSTGRES_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/study_support_app
    steps:
      - checkout:
          path: ~/study_support_app
      - ruby/install-deps
      - run: yarn install
      - run: mv config/database.yml.ci config/database.yml
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: Rubocop
          command: bundle exec rubocop --fail-level W --display-only-fail-level-offenses
      - ruby/rspec-test

  deploy:
    docker:
      - image: circleci/ruby:2.6-node
    working_directory: ~/study_support_app
    steps:
      - checkout:
          path: ~/study_support_app
      - ruby/install-deps
      - run: yarn install
      - add_ssh_keys:
          fingerprints: "b1:7a:9c:69:81:41:33:5a:e4:94:6c:8c:b3:06:28:67"
      - deploy:
          name: Capistrano deploy
          command: bundle exec cap production deploy

workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
