version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/study_support_app
    steps:
      - checkout:
        path: ~/study_support_app
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.6
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: app_user_role
          POSTGRES_DB: study_support_app_test
          POSTGRES_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/study_support_app
    steps:
      - checkout:
        path: ~/study_support_app
      - ruby/install-deps
      - run:
        name: Database setup
        command: bundle exec rails db:migrate
      - run:
        name: Rubocop
        command: bundle exec rubocop --fail-level W --display-only-fail-level-offenses
      - run:
        name: Rspec
        command: bundle exec rspec --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format documentation

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
