version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
    working_directory: ~/study_support_app
    steps:
      - checkout:
          path: ~/study_support_app
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: 'yarn.lock'

  test:
    docker:
      - image: circleci/ruby:2.6
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: app_user_role
          POSTGRES_DB: study_support_app_test
          POSTGRES_PASSWORD: password
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/study_support_app
    steps:
      - checkout:
          path: ~/study_support_app
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: 'yarn.lock'
      - run: mv config/database.yml.ci config/database.yml
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: Rubocop
          command: bundle exec rubocop --fail-level W --display-only-fail-level-offenses
      - ruby/rspec-test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
